name: fnmwebui

services:
  db:
    image: mariadb:10.5
    container_name: fnmwebui_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  fnmwebui:
    image: pumtrix/fnm-webui:latest
    container_name: fnmwebui
    hostname: fnmwebui
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "0.0.0.0:8000:8000"

    depends_on:
      - db
    volumes:
      - "./fnmwebui:/data"
    env_file:
      - "./fnmwebui.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always

  fsgui-django:
    build: ../../fnm-fsgui/.
    container_name: fsgui-django
    ports:
      - "8024:8024"
    env_file:
      - ../../fnm-fsgui/.env
    volumes:
      - ../../fnm-fsgui:/app
    command: bash -c "python manage.py runserver 0.0.0.0:8024" 
    restart: always